---
title: Project Review Template 
author: Murphy John
date: date-modified
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Early Cardiovascular Disease Risk Among Younger Individuals with Normal Cholesterol: The Role of Elevated Blood Pressure and ST Depression

Name of project author(s): Murtaza Yaqubi

Name of project reviewer: Murphy John


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

- Add references in your intro
- Elaborate on the importance or motivation for your research question. Is there any prior evidence of an association? Why is this an important topic to explore?
- Why are you restricting the age to under 50? It looks like you have data for other ages. If you want to emphasis that this study is looking in young adults then include more background on CVD prevalence in young adults. Maybe there are different risk factors in this age group compared to older individuals? That could provide more motivation for your research question.

### Summary assessment
* some contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

- Line 17, say "individuals under 50 years of age" or something to clarify the age range.
- What do you hypothesize? Why do you think that?

### Summary assessment
* question/hypotheses somewhat explained


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

- Line 25, just say "the primary outcome is presence or absence of heart disease". I'm not sure what the word target means in this sentence.
- Add a reference to line 23 "These thresholds were chosen based on clinical relevance".
- Talk more about the data source. Where did it come from (what specific hospital)? When was it collected? Who was included in the data collection? What was the inclusion/exclusion criteria for this study? 
- BMI, family history, SES, and smoking status are confounders of CVD. If you have data on these, include it. If not, this needs to be discussed in the limitations.
- Your study population needs to be more specific. Is it adults worldwide? In India? In a specific area of India?
- What is oldpeak?
- After the inclusion/exclusion critera, how many individuals/obervation are in your data?

### Summary assessment
* source and overall structure of data somewhat explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

- You need to load your processed data at the start of each script. None of your scripts are running because of this. To make sure everything works and is reproducible, clear your environment before you run anything in a new script.
- The data processing looks good so far but you should include your inclusion/exclusion criteria in that script (ie filter age < 50). 
- Your eda should be of the data used in your analysis (ie age < 50). This will likely change your findings and perhaps your analysis decisions.
- Your plots look nice.

### Summary assessment
* some weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

- You have processing code in your analysis-code/01_inferential_stats.qmd file. This should be in the processing code file. You also have eda in this file that should go in the eda folder.

In analysis-code/02_modeling.qmd:

- Why are you fitting linear models to a binary variable?
- Use logistic regression instead of linear.
- If you want to use lasso, use logistic_reg() in your spec.
- For your random forest model, set mode to "Classification" instead of regression.
- RMSE is for continuous outcomes, use AUC and/or accuracy for your metrics instead.
- Use test/train data split and/or cross-validation for model selection.

analysis-code/03_model_tuning.qmd:

- You need to load your model objects from the previous scripts or merge this script with the previous one.
- It doesn't make sense to use rmse for metrics
- You need to use binary outcome modeling methods in the modeling script then update this script (or merge the two)

### Summary assessment
* wrong/inadequate analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

- The descriptive statistics table should be of the data you analyze (age < 50).
- The tables and figures need to render to the manuscript doc

### Summary assessment
* results are presented ok, with room for improvement

## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

- For the current analysis set up, the discussion is set up well. Once you implement the correct analysis methods you'll likely get different results.
- Your limitations sections needs to address the confounders that you don't control for. Also if there are any data collection limitations list that here.

### Summary assessment
* minor parts wrong, missing or unclear

# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

- Project structure looks good.
- Your analysis code contains some data processing and eda that should be in different locations.

### Summary assessment
* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

- looks good

### Summary assessment
* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

- Your manuscript wouldn't render as is. You need to fix your figures and tables code.
- None of your eda or analysis scripts run because you haven't loaded the data in them. Use cardio_df <- readRDS(here::here("data/processed-data/cleaned_df.rds"))
- Project is not reproducible- you need to load data and model objects in each script.

### Summary assessment
* small parts not reproducible or required manual intervention 

## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Given the data presented, the project analysis is thorough. It isn't correct in the current methods but with minor edits, you should get more appropriate results. My biggest concerns are the eda on the unused data, the incorrect modeling methods, and the lack of control for major CVD confounders.

### Summary assessment
* strong level of thoroughness


## Further comments

- References are not properly loaded. Consider using .bib file. Zotero is a nice software for storing references and generating .bib files.




