---
title: Project Review Template 
author: YOUR NAME
date: date-modified
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Early Cardiovascular Disease Risk Among Younger Individuals with Normal Cholesterol: The Role of Elevated Blood Pressure and ST Depression

Name of project author(s): Murtaza Yaqubi

Name of project reviewer: Alexis Gonzalez




# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The introduction needs contexualization. Why is this issue important? What is the current scope? Maybe provide some global statistics and some India specific statistics.

### Summary Assessment 

* some contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

Question is clear, I understand your goal.

### Summary assessment
* question/hypotheses unclear



## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

I do not really understand the dataset. How was this data obtained, where is this hospital specifically? Might be good to include some parts of the dataset description from the website you got it from.

### Summary assessment

* source and overall structure of data somewhat explained



## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

Unfortunately, I am unable to load the data in your manuscript. I still want to give feedback so I will look at your code file.

- Instead of the basic table output consider using flextable for KableExtra
- It doesn't look like you include any of your figures from EDA. Those are actually very helpful for getting an idea of distributions and burden.
- The EDA should help explain the formulation of your question or provide some reason why.
- The code is very very neat and the graphs look great!!

### Summary assessment

* some weaknesses in wrangling and exploratory component


## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

I do not think you need the linear model here for a binary outcome, the log model makes more sense.

### Summary assessment

* defensible but not optimal analysis 


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

I like how the results section is sectioned out, makes it easy to follow. Figures look nice.

### Summary assessment

* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The discussion is lacking in explanation of the results. 

### Summary assessment
 * minor parts wrong, missing or unclear 



## Further comments

_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

Porject is structured well, easy to follow

### Summary assessment

* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

Code is well documented and easy to follow

### Summary assessment

* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

The manuscript needs to be fixed and I was unable to run the cross validation for your RF model


### Summary assessment

* small parts not reproducible or required manual intervention 



## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Overall I would say the study was thorough. I think you should go back and expand on your introduction, discussion and conclusion. Explain the reason for using LASSO and RF. Also make sure to add some EDA plots into your manuscript.

### Summary assessment

* decent level of thorougness


## Further comments

don't forget to properly format references! This is a great study I can't wait to read the final product.





